// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_CreateNode_FullMethodName              = "/storage.StorageService/CreateNode"
	StorageService_GetNode_FullMethodName                 = "/storage.StorageService/GetNode"
	StorageService_GetNodeBulk_FullMethodName             = "/storage.StorageService/GetNodeBulk"
	StorageService_UpdateNode_FullMethodName              = "/storage.StorageService/UpdateNode"
	StorageService_DeleteNode_FullMethodName              = "/storage.StorageService/DeleteNode"
	StorageService_DeleteNodeBulk_FullMethodName          = "/storage.StorageService/DeleteNodeBulk"
	StorageService_ContainsNode_FullMethodName            = "/storage.StorageService/ContainsNode"
	StorageService_PeekNode_FullMethodName                = "/storage.StorageService/PeekNode"
	StorageService_CreateEdge_FullMethodName              = "/storage.StorageService/CreateEdge"
	StorageService_GetEdge_FullMethodName                 = "/storage.StorageService/GetEdge"
	StorageService_GetEdgeBulk_FullMethodName             = "/storage.StorageService/GetEdgeBulk"
	StorageService_UpdateEdge_FullMethodName              = "/storage.StorageService/UpdateEdge"
	StorageService_DeleteEdge_FullMethodName              = "/storage.StorageService/DeleteEdge"
	StorageService_DeleteEdgeBulk_FullMethodName          = "/storage.StorageService/DeleteEdgeBulk"
	StorageService_ContainsEdge_FullMethodName            = "/storage.StorageService/ContainsEdge"
	StorageService_PeekEdge_FullMethodName                = "/storage.StorageService/PeekEdge"
	StorageService_GetDegree_FullMethodName               = "/storage.StorageService/GetDegree"
	StorageService_GetDegreeBatch_FullMethodName          = "/storage.StorageService/GetDegreeBatch"
	StorageService_HasEdge_FullMethodName                 = "/storage.StorageService/HasEdge"
	StorageService_HasEdgeBatch_FullMethodName            = "/storage.StorageService/HasEdgeBatch"
	StorageService_GetEdgeWeight_FullMethodName           = "/storage.StorageService/GetEdgeWeight"
	StorageService_GetEdgeWeightsBatch_FullMethodName     = "/storage.StorageService/GetEdgeWeightsBatch"
	StorageService_GetCommonNeighbors_FullMethodName      = "/storage.StorageService/GetCommonNeighbors"
	StorageService_CountCommonNeighbors_FullMethodName    = "/storage.StorageService/CountCommonNeighbors"
	StorageService_GetNeighbors_FullMethodName            = "/storage.StorageService/GetNeighbors"
	StorageService_GetNeighborsBatch_FullMethodName       = "/storage.StorageService/GetNeighborsBatch"
	StorageService_GetNeighborsWithWeights_FullMethodName = "/storage.StorageService/GetNeighborsWithWeights"
	StorageService_ShortestPath_FullMethodName            = "/storage.StorageService/ShortestPath"
	StorageService_IsNeighbor_FullMethodName              = "/storage.StorageService/IsNeighbor"
	StorageService_GetStats_FullMethodName                = "/storage.StorageService/GetStats"
	StorageService_GetCacheStats_FullMethodName           = "/storage.StorageService/GetCacheStats"
	StorageService_ClearCache_FullMethodName              = "/storage.StorageService/ClearCache"
	StorageService_PrefetchViewport_FullMethodName        = "/storage.StorageService/PrefetchViewport"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---- Service Definition ----
type StorageServiceClient interface {
	// Node Operations
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	GetNodeBulk(ctx context.Context, in *GetNodeBulkRequest, opts ...grpc.CallOption) (*GetNodeBulkResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	DeleteNodeBulk(ctx context.Context, in *DeleteNodeBulkRequest, opts ...grpc.CallOption) (*DeleteNodeBulkResponse, error)
	ContainsNode(ctx context.Context, in *ContainsNodeRequest, opts ...grpc.CallOption) (*ContainsNodeResponse, error)
	PeekNode(ctx context.Context, in *PeekNodeRequest, opts ...grpc.CallOption) (*PeekNodeResponse, error)
	// Edge Operations
	CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*CreateEdgeResponse, error)
	GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*GetEdgeResponse, error)
	GetEdgeBulk(ctx context.Context, in *GetEdgeBulkRequest, opts ...grpc.CallOption) (*GetEdgeBulkResponse, error)
	UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...grpc.CallOption) (*UpdateEdgeResponse, error)
	DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error)
	DeleteEdgeBulk(ctx context.Context, in *DeleteEdgeBulkRequest, opts ...grpc.CallOption) (*DeleteEdgeBulkResponse, error)
	ContainsEdge(ctx context.Context, in *ContainsEdgeRequest, opts ...grpc.CallOption) (*ContainsEdgeResponse, error)
	PeekEdge(ctx context.Context, in *PeekEdgeRequest, opts ...grpc.CallOption) (*PeekEdgeResponse, error)
	// Graph Operations (New)
	GetDegree(ctx context.Context, in *GetDegreeRequest, opts ...grpc.CallOption) (*GetDegreeResponse, error)
	GetDegreeBatch(ctx context.Context, in *GetDegreeBatchRequest, opts ...grpc.CallOption) (*GetDegreeBatchResponse, error)
	HasEdge(ctx context.Context, in *HasEdgeRequest, opts ...grpc.CallOption) (*HasEdgeResponse, error)
	HasEdgeBatch(ctx context.Context, in *HasEdgeBatchRequest, opts ...grpc.CallOption) (*HasEdgeBatchResponse, error)
	GetEdgeWeight(ctx context.Context, in *GetEdgeWeightRequest, opts ...grpc.CallOption) (*GetEdgeWeightResponse, error)
	GetEdgeWeightsBatch(ctx context.Context, in *GetEdgeWeightsBatchRequest, opts ...grpc.CallOption) (*GetEdgeWeightsBatchResponse, error)
	GetCommonNeighbors(ctx context.Context, in *GetCommonNeighborsRequest, opts ...grpc.CallOption) (*GetCommonNeighborsResponse, error)
	CountCommonNeighbors(ctx context.Context, in *CountCommonNeighborsRequest, opts ...grpc.CallOption) (*CountCommonNeighborsResponse, error)
	GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error)
	GetNeighborsBatch(ctx context.Context, in *GetNeighborsBatchRequest, opts ...grpc.CallOption) (*GetNeighborsBatchResponse, error)
	GetNeighborsWithWeights(ctx context.Context, in *GetNeighborsWithWeightsRequest, opts ...grpc.CallOption) (*GetNeighborsWithWeightsResponse, error)
	ShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error)
	IsNeighbor(ctx context.Context, in *IsNeighborRequest, opts ...grpc.CallOption) (*IsNeighborResponse, error)
	// Admin Operations
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	GetCacheStats(ctx context.Context, in *GetCacheStatsRequest, opts ...grpc.CallOption) (*GetCacheStatsResponse, error)
	ClearCache(ctx context.Context, in *ClearCacheRequest, opts ...grpc.CallOption) (*ClearCacheResponse, error)
	PrefetchViewport(ctx context.Context, in *PrefetchViewportRequest, opts ...grpc.CallOption) (*PrefetchViewportResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, StorageService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetNodeBulk(ctx context.Context, in *GetNodeBulkRequest, opts ...grpc.CallOption) (*GetNodeBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeBulkResponse)
	err := c.cc.Invoke(ctx, StorageService_GetNodeBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodeResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteNodeBulk(ctx context.Context, in *DeleteNodeBulkRequest, opts ...grpc.CallOption) (*DeleteNodeBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodeBulkResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteNodeBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ContainsNode(ctx context.Context, in *ContainsNodeRequest, opts ...grpc.CallOption) (*ContainsNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainsNodeResponse)
	err := c.cc.Invoke(ctx, StorageService_ContainsNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) PeekNode(ctx context.Context, in *PeekNodeRequest, opts ...grpc.CallOption) (*PeekNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeekNodeResponse)
	err := c.cc.Invoke(ctx, StorageService_PeekNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*CreateEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*GetEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_GetEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetEdgeBulk(ctx context.Context, in *GetEdgeBulkRequest, opts ...grpc.CallOption) (*GetEdgeBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeBulkResponse)
	err := c.cc.Invoke(ctx, StorageService_GetEdgeBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...grpc.CallOption) (*UpdateEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteEdgeBulk(ctx context.Context, in *DeleteEdgeBulkRequest, opts ...grpc.CallOption) (*DeleteEdgeBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEdgeBulkResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteEdgeBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ContainsEdge(ctx context.Context, in *ContainsEdgeRequest, opts ...grpc.CallOption) (*ContainsEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainsEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_ContainsEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) PeekEdge(ctx context.Context, in *PeekEdgeRequest, opts ...grpc.CallOption) (*PeekEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeekEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_PeekEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetDegree(ctx context.Context, in *GetDegreeRequest, opts ...grpc.CallOption) (*GetDegreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDegreeResponse)
	err := c.cc.Invoke(ctx, StorageService_GetDegree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetDegreeBatch(ctx context.Context, in *GetDegreeBatchRequest, opts ...grpc.CallOption) (*GetDegreeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDegreeBatchResponse)
	err := c.cc.Invoke(ctx, StorageService_GetDegreeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) HasEdge(ctx context.Context, in *HasEdgeRequest, opts ...grpc.CallOption) (*HasEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasEdgeResponse)
	err := c.cc.Invoke(ctx, StorageService_HasEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) HasEdgeBatch(ctx context.Context, in *HasEdgeBatchRequest, opts ...grpc.CallOption) (*HasEdgeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasEdgeBatchResponse)
	err := c.cc.Invoke(ctx, StorageService_HasEdgeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetEdgeWeight(ctx context.Context, in *GetEdgeWeightRequest, opts ...grpc.CallOption) (*GetEdgeWeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeWeightResponse)
	err := c.cc.Invoke(ctx, StorageService_GetEdgeWeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetEdgeWeightsBatch(ctx context.Context, in *GetEdgeWeightsBatchRequest, opts ...grpc.CallOption) (*GetEdgeWeightsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeWeightsBatchResponse)
	err := c.cc.Invoke(ctx, StorageService_GetEdgeWeightsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetCommonNeighbors(ctx context.Context, in *GetCommonNeighborsRequest, opts ...grpc.CallOption) (*GetCommonNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommonNeighborsResponse)
	err := c.cc.Invoke(ctx, StorageService_GetCommonNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CountCommonNeighbors(ctx context.Context, in *CountCommonNeighborsRequest, opts ...grpc.CallOption) (*CountCommonNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountCommonNeighborsResponse)
	err := c.cc.Invoke(ctx, StorageService_CountCommonNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNeighborsResponse)
	err := c.cc.Invoke(ctx, StorageService_GetNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetNeighborsBatch(ctx context.Context, in *GetNeighborsBatchRequest, opts ...grpc.CallOption) (*GetNeighborsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNeighborsBatchResponse)
	err := c.cc.Invoke(ctx, StorageService_GetNeighborsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetNeighborsWithWeights(ctx context.Context, in *GetNeighborsWithWeightsRequest, opts ...grpc.CallOption) (*GetNeighborsWithWeightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNeighborsWithWeightsResponse)
	err := c.cc.Invoke(ctx, StorageService_GetNeighborsWithWeights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortestPathResponse)
	err := c.cc.Invoke(ctx, StorageService_ShortestPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) IsNeighbor(ctx context.Context, in *IsNeighborRequest, opts ...grpc.CallOption) (*IsNeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsNeighborResponse)
	err := c.cc.Invoke(ctx, StorageService_IsNeighbor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, StorageService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetCacheStats(ctx context.Context, in *GetCacheStatsRequest, opts ...grpc.CallOption) (*GetCacheStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCacheStatsResponse)
	err := c.cc.Invoke(ctx, StorageService_GetCacheStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ClearCache(ctx context.Context, in *ClearCacheRequest, opts ...grpc.CallOption) (*ClearCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearCacheResponse)
	err := c.cc.Invoke(ctx, StorageService_ClearCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) PrefetchViewport(ctx context.Context, in *PrefetchViewportRequest, opts ...grpc.CallOption) (*PrefetchViewportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefetchViewportResponse)
	err := c.cc.Invoke(ctx, StorageService_PrefetchViewport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// ---- Service Definition ----
type StorageServiceServer interface {
	// Node Operations
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	GetNodeBulk(context.Context, *GetNodeBulkRequest) (*GetNodeBulkResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	DeleteNodeBulk(context.Context, *DeleteNodeBulkRequest) (*DeleteNodeBulkResponse, error)
	ContainsNode(context.Context, *ContainsNodeRequest) (*ContainsNodeResponse, error)
	PeekNode(context.Context, *PeekNodeRequest) (*PeekNodeResponse, error)
	// Edge Operations
	CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeResponse, error)
	GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error)
	GetEdgeBulk(context.Context, *GetEdgeBulkRequest) (*GetEdgeBulkResponse, error)
	UpdateEdge(context.Context, *UpdateEdgeRequest) (*UpdateEdgeResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error)
	DeleteEdgeBulk(context.Context, *DeleteEdgeBulkRequest) (*DeleteEdgeBulkResponse, error)
	ContainsEdge(context.Context, *ContainsEdgeRequest) (*ContainsEdgeResponse, error)
	PeekEdge(context.Context, *PeekEdgeRequest) (*PeekEdgeResponse, error)
	// Graph Operations (New)
	GetDegree(context.Context, *GetDegreeRequest) (*GetDegreeResponse, error)
	GetDegreeBatch(context.Context, *GetDegreeBatchRequest) (*GetDegreeBatchResponse, error)
	HasEdge(context.Context, *HasEdgeRequest) (*HasEdgeResponse, error)
	HasEdgeBatch(context.Context, *HasEdgeBatchRequest) (*HasEdgeBatchResponse, error)
	GetEdgeWeight(context.Context, *GetEdgeWeightRequest) (*GetEdgeWeightResponse, error)
	GetEdgeWeightsBatch(context.Context, *GetEdgeWeightsBatchRequest) (*GetEdgeWeightsBatchResponse, error)
	GetCommonNeighbors(context.Context, *GetCommonNeighborsRequest) (*GetCommonNeighborsResponse, error)
	CountCommonNeighbors(context.Context, *CountCommonNeighborsRequest) (*CountCommonNeighborsResponse, error)
	GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error)
	GetNeighborsBatch(context.Context, *GetNeighborsBatchRequest) (*GetNeighborsBatchResponse, error)
	GetNeighborsWithWeights(context.Context, *GetNeighborsWithWeightsRequest) (*GetNeighborsWithWeightsResponse, error)
	ShortestPath(context.Context, *ShortestPathRequest) (*ShortestPathResponse, error)
	IsNeighbor(context.Context, *IsNeighborRequest) (*IsNeighborResponse, error)
	// Admin Operations
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	GetCacheStats(context.Context, *GetCacheStatsRequest) (*GetCacheStatsResponse, error)
	ClearCache(context.Context, *ClearCacheRequest) (*ClearCacheResponse, error)
	PrefetchViewport(context.Context, *PrefetchViewportRequest) (*PrefetchViewportResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedStorageServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedStorageServiceServer) GetNodeBulk(context.Context, *GetNodeBulkRequest) (*GetNodeBulkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeBulk not implemented")
}
func (UnimplementedStorageServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedStorageServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedStorageServiceServer) DeleteNodeBulk(context.Context, *DeleteNodeBulkRequest) (*DeleteNodeBulkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNodeBulk not implemented")
}
func (UnimplementedStorageServiceServer) ContainsNode(context.Context, *ContainsNodeRequest) (*ContainsNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContainsNode not implemented")
}
func (UnimplementedStorageServiceServer) PeekNode(context.Context, *PeekNodeRequest) (*PeekNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeekNode not implemented")
}
func (UnimplementedStorageServiceServer) CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEdge not implemented")
}
func (UnimplementedStorageServiceServer) GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdge not implemented")
}
func (UnimplementedStorageServiceServer) GetEdgeBulk(context.Context, *GetEdgeBulkRequest) (*GetEdgeBulkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdgeBulk not implemented")
}
func (UnimplementedStorageServiceServer) UpdateEdge(context.Context, *UpdateEdgeRequest) (*UpdateEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEdge not implemented")
}
func (UnimplementedStorageServiceServer) DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedStorageServiceServer) DeleteEdgeBulk(context.Context, *DeleteEdgeBulkRequest) (*DeleteEdgeBulkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdgeBulk not implemented")
}
func (UnimplementedStorageServiceServer) ContainsEdge(context.Context, *ContainsEdgeRequest) (*ContainsEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContainsEdge not implemented")
}
func (UnimplementedStorageServiceServer) PeekEdge(context.Context, *PeekEdgeRequest) (*PeekEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeekEdge not implemented")
}
func (UnimplementedStorageServiceServer) GetDegree(context.Context, *GetDegreeRequest) (*GetDegreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDegree not implemented")
}
func (UnimplementedStorageServiceServer) GetDegreeBatch(context.Context, *GetDegreeBatchRequest) (*GetDegreeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDegreeBatch not implemented")
}
func (UnimplementedStorageServiceServer) HasEdge(context.Context, *HasEdgeRequest) (*HasEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasEdge not implemented")
}
func (UnimplementedStorageServiceServer) HasEdgeBatch(context.Context, *HasEdgeBatchRequest) (*HasEdgeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasEdgeBatch not implemented")
}
func (UnimplementedStorageServiceServer) GetEdgeWeight(context.Context, *GetEdgeWeightRequest) (*GetEdgeWeightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdgeWeight not implemented")
}
func (UnimplementedStorageServiceServer) GetEdgeWeightsBatch(context.Context, *GetEdgeWeightsBatchRequest) (*GetEdgeWeightsBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdgeWeightsBatch not implemented")
}
func (UnimplementedStorageServiceServer) GetCommonNeighbors(context.Context, *GetCommonNeighborsRequest) (*GetCommonNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommonNeighbors not implemented")
}
func (UnimplementedStorageServiceServer) CountCommonNeighbors(context.Context, *CountCommonNeighborsRequest) (*CountCommonNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountCommonNeighbors not implemented")
}
func (UnimplementedStorageServiceServer) GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNeighbors not implemented")
}
func (UnimplementedStorageServiceServer) GetNeighborsBatch(context.Context, *GetNeighborsBatchRequest) (*GetNeighborsBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNeighborsBatch not implemented")
}
func (UnimplementedStorageServiceServer) GetNeighborsWithWeights(context.Context, *GetNeighborsWithWeightsRequest) (*GetNeighborsWithWeightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNeighborsWithWeights not implemented")
}
func (UnimplementedStorageServiceServer) ShortestPath(context.Context, *ShortestPathRequest) (*ShortestPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShortestPath not implemented")
}
func (UnimplementedStorageServiceServer) IsNeighbor(context.Context, *IsNeighborRequest) (*IsNeighborResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsNeighbor not implemented")
}
func (UnimplementedStorageServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedStorageServiceServer) GetCacheStats(context.Context, *GetCacheStatsRequest) (*GetCacheStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCacheStats not implemented")
}
func (UnimplementedStorageServiceServer) ClearCache(context.Context, *ClearCacheRequest) (*ClearCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearCache not implemented")
}
func (UnimplementedStorageServiceServer) PrefetchViewport(context.Context, *PrefetchViewportRequest) (*PrefetchViewportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrefetchViewport not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetNodeBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetNodeBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetNodeBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetNodeBulk(ctx, req.(*GetNodeBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteNodeBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteNodeBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteNodeBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteNodeBulk(ctx, req.(*DeleteNodeBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ContainsNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainsNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ContainsNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ContainsNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ContainsNode(ctx, req.(*ContainsNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_PeekNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PeekNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_PeekNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PeekNode(ctx, req.(*PeekNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateEdge(ctx, req.(*CreateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetEdge(ctx, req.(*GetEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetEdgeBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetEdgeBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetEdgeBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetEdgeBulk(ctx, req.(*GetEdgeBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateEdge(ctx, req.(*UpdateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteEdge(ctx, req.(*DeleteEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteEdgeBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteEdgeBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteEdgeBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteEdgeBulk(ctx, req.(*DeleteEdgeBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ContainsEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainsEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ContainsEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ContainsEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ContainsEdge(ctx, req.(*ContainsEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_PeekEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PeekEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_PeekEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PeekEdge(ctx, req.(*PeekEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetDegree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDegreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetDegree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetDegree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetDegree(ctx, req.(*GetDegreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetDegreeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDegreeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetDegreeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetDegreeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetDegreeBatch(ctx, req.(*GetDegreeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_HasEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).HasEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_HasEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).HasEdge(ctx, req.(*HasEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_HasEdgeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasEdgeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).HasEdgeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_HasEdgeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).HasEdgeBatch(ctx, req.(*HasEdgeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetEdgeWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetEdgeWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetEdgeWeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetEdgeWeight(ctx, req.(*GetEdgeWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetEdgeWeightsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeWeightsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetEdgeWeightsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetEdgeWeightsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetEdgeWeightsBatch(ctx, req.(*GetEdgeWeightsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetCommonNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommonNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetCommonNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetCommonNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetCommonNeighbors(ctx, req.(*GetCommonNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CountCommonNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountCommonNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CountCommonNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CountCommonNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CountCommonNeighbors(ctx, req.(*CountCommonNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetNeighbors(ctx, req.(*GetNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetNeighborsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNeighborsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetNeighborsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetNeighborsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetNeighborsBatch(ctx, req.(*GetNeighborsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetNeighborsWithWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNeighborsWithWeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetNeighborsWithWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetNeighborsWithWeights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetNeighborsWithWeights(ctx, req.(*GetNeighborsWithWeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ShortestPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortestPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ShortestPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ShortestPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ShortestPath(ctx, req.(*ShortestPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_IsNeighbor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsNeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).IsNeighbor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_IsNeighbor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).IsNeighbor(ctx, req.(*IsNeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetCacheStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetCacheStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetCacheStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetCacheStats(ctx, req.(*GetCacheStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ClearCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ClearCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ClearCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ClearCache(ctx, req.(*ClearCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_PrefetchViewport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrefetchViewportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PrefetchViewport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_PrefetchViewport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PrefetchViewport(ctx, req.(*PrefetchViewportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _StorageService_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _StorageService_GetNode_Handler,
		},
		{
			MethodName: "GetNodeBulk",
			Handler:    _StorageService_GetNodeBulk_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _StorageService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _StorageService_DeleteNode_Handler,
		},
		{
			MethodName: "DeleteNodeBulk",
			Handler:    _StorageService_DeleteNodeBulk_Handler,
		},
		{
			MethodName: "ContainsNode",
			Handler:    _StorageService_ContainsNode_Handler,
		},
		{
			MethodName: "PeekNode",
			Handler:    _StorageService_PeekNode_Handler,
		},
		{
			MethodName: "CreateEdge",
			Handler:    _StorageService_CreateEdge_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _StorageService_GetEdge_Handler,
		},
		{
			MethodName: "GetEdgeBulk",
			Handler:    _StorageService_GetEdgeBulk_Handler,
		},
		{
			MethodName: "UpdateEdge",
			Handler:    _StorageService_UpdateEdge_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _StorageService_DeleteEdge_Handler,
		},
		{
			MethodName: "DeleteEdgeBulk",
			Handler:    _StorageService_DeleteEdgeBulk_Handler,
		},
		{
			MethodName: "ContainsEdge",
			Handler:    _StorageService_ContainsEdge_Handler,
		},
		{
			MethodName: "PeekEdge",
			Handler:    _StorageService_PeekEdge_Handler,
		},
		{
			MethodName: "GetDegree",
			Handler:    _StorageService_GetDegree_Handler,
		},
		{
			MethodName: "GetDegreeBatch",
			Handler:    _StorageService_GetDegreeBatch_Handler,
		},
		{
			MethodName: "HasEdge",
			Handler:    _StorageService_HasEdge_Handler,
		},
		{
			MethodName: "HasEdgeBatch",
			Handler:    _StorageService_HasEdgeBatch_Handler,
		},
		{
			MethodName: "GetEdgeWeight",
			Handler:    _StorageService_GetEdgeWeight_Handler,
		},
		{
			MethodName: "GetEdgeWeightsBatch",
			Handler:    _StorageService_GetEdgeWeightsBatch_Handler,
		},
		{
			MethodName: "GetCommonNeighbors",
			Handler:    _StorageService_GetCommonNeighbors_Handler,
		},
		{
			MethodName: "CountCommonNeighbors",
			Handler:    _StorageService_CountCommonNeighbors_Handler,
		},
		{
			MethodName: "GetNeighbors",
			Handler:    _StorageService_GetNeighbors_Handler,
		},
		{
			MethodName: "GetNeighborsBatch",
			Handler:    _StorageService_GetNeighborsBatch_Handler,
		},
		{
			MethodName: "GetNeighborsWithWeights",
			Handler:    _StorageService_GetNeighborsWithWeights_Handler,
		},
		{
			MethodName: "ShortestPath",
			Handler:    _StorageService_ShortestPath_Handler,
		},
		{
			MethodName: "IsNeighbor",
			Handler:    _StorageService_IsNeighbor_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _StorageService_GetStats_Handler,
		},
		{
			MethodName: "GetCacheStats",
			Handler:    _StorageService_GetCacheStats_Handler,
		},
		{
			MethodName: "ClearCache",
			Handler:    _StorageService_ClearCache_Handler,
		},
		{
			MethodName: "PrefetchViewport",
			Handler:    _StorageService_PrefetchViewport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/storage.proto",
}
