# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00

from logger_config import (
    get_logger,
)
from fastapi.responses import FileResponse

from schemas.backup import (
    BackupCreateRequest,
)

from services.network_service import (
    NetworkService,
)

from core.graph_instance import (
    graph_service,
)
from fastapi import APIRouter


logger = get_logger(__name__)
router = APIRouter(tags=['Backups'])

network_service = NetworkService(
    graph_service
)

@router.get(
    '/backups',
    tags=['Backups'],
)
async def get_backups():
    logger.debug(
        "Backup list requested"
    )
    return (
        network_service
        .backups()
    )


@router.post(
    '/backups',
    tags=['Backups'],
)
async def create_backup(
        req: BackupCreateRequest | None = None,
):
    logger.info(
        "Backup creation requested"
    )

    return network_service.create_backup(
        req.name if req else None
    )


@router.delete(
    '/backups/{backup_id}',
    tags=['Backups'],
)
def delete_backup(backup_id: str):
    return network_service.delete_backup(
        backup_id
    )


@router.get(
    "/backups/{backup_id}/download",
    tags=["Backups"],
)
async def download_backup(
        backup_id: str,
):
    backup_file = (
        network_service
        .download_backup_file(
            backup_id
        )
    )

    return FileResponse(
        path=backup_file,
        filename=f"{backup_id}.json.gz",
        media_type="application/gzip",
    )


@router.post(
    '/backups/{backup_id}/restore',
    tags=['Backups'],
)
async def restore_backup(backup_id: str):
    return network_service.get_backup(
        backup_id
    )
