# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00


from fastapi import APIRouter,HTTPException
from logger_config import (
    get_logger,
)
from services.network_service import (
    NetworkService,
)

from core.exceptions import (
    GraphNotFoundError,
)
from core.graph_instance import (
    graph_service,
)

logger = get_logger(__name__)

router = APIRouter(tags=['Graphs'])

network_service = NetworkService(
    graph_service
)

@router.get(
    '/graphs',
    tags=['Graphs'],
)
async def graphs():
    return network_service.graphs()


@router.post(
    '/graphs/{graph_id}/switch',
    tags=['Graphs'],
)
def switch_graph(graph_id: str):
    try:

        return (
            network_service
            .switch_graph(
                graph_id
            )
        )


    except GraphNotFoundError as e:
        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )
