# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00

from logger_config import get_logger
from services.analytic_service import AnalyticsService
from core.graph_instance import graph_service
from core.exceptions import (
    SocialTribeException,
)
from schemas.graph_view import (
    Node,
    Edge,
)
from schemas.dataset_import import (
    DatasetImportResponse,
)

from fastapi import (
    APIRouter,
    HTTPException,
    UploadFile,
    File,
    Query,
)

from schemas.community import (
    EnsembleCommunityRequest,
)

from schemas.analytics import (
    ShortestPathRequest,
    CommonNeighborsRequest
)
from services.network_service import NetworkService

logger = get_logger(__name__)

router = APIRouter(tags=['Graph'])

analytics_service = AnalyticsService(graph_service)
network_service = NetworkService(graph_service)


@router.post(
    '/graph/common-neighbors',
    tags=['Graph'],
)
def find_common_neighbors(body: CommonNeighborsRequest):
    try:
        return analytics_service.common_neighbors(
            body.source_id,
            body.target_id,
        )

    except SocialTribeException as e:

        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.post(
    '/graph/edges',
    tags=['Graph'],
)
def create_edge(body: Edge):
    try:

        return network_service.create_or_update_edge(
            body
        )


    except SocialTribeException as e:

        logger.exception(

            "Create edge failed"

        )
        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.delete(
    '/graph/edges/{edge_id}',
    tags=['Graph'],
)
def delete_edge(edge_id: str):
    logger.info(
        "Delete node request %s",
        edge_id,
    )

    ok = network_service.delete_edge(
        edge_id
    )

    try:
        if not ok:
            raise HTTPException(
                status_code=404,
                detail="Edge not found",
            )

        return {
            "success": True
        }
    except SocialTribeException as e:
        raise HTTPException(
            422,
            e.to_dict(),
        )


@router.post(
    '/graph/ensemble-communities',
    tags=['Graph'],
)
def detect_ensemble_communities(
        body: EnsembleCommunityRequest,
):
    try:
        return (
            analytics_service
            .detect_communities(
                body
            )
        )

    except SocialTribeException as e:

        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.post(
    '/graph/import-dataset',
    tags=['Graph'],
)
async def import_dataset(
        mode: str = Query(
            "switch",
            pattern="^(switch|merge)$",
        ),
        file: UploadFile = File(...),
):
    allowed = (
        ".txt",
        ".csv",
        ".json",
        ".pdf",
        ".graphml",
    )

    if not file.filename.lower().endswith(
            allowed
    ):
        raise HTTPException(
            status_code=422,
            detail=(
                "Supported formats: "
                "txt, csv, json, pdf, graphml"
            ),
        )

    try:

        file_bytes = await file.read()

        result = (
            network_service.import_dataset(
                file.filename,
                file_bytes,
                mode,
            )
        )

        return DatasetImportResponse(
            **result
        )

    except SocialTribeException as e:
        logger.exception(

            "Dataset import failed"

        )
        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.get(
    '/graph/metadata',
    tags=['Graph'],
)
def get_graph_metadata():
    logger.debug(
        "Metadata requested"
    )
    return analytics_service.get_metadata()


@router.get(
    '/graph/network',
    tags=['Graph'],
)
def export_graph():
    logger.info(
        "Graph export requested"
    )
    return analytics_service.export_reactflow()


@router.post(
    '/graph/nodes',
    tags=['Graph'],
)
def create_node(body: Node):
    try:

        return network_service.create_or_update_node(
            body
        )


    except SocialTribeException as e:

        logger.exception(

            "Create node failed"

        )

        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.patch(
    '/graph/nodes/{node_id}',
    tags=['Graph'],
)
def update_node(
        node_id: str,
        node: Node,
):
    logger.info(
        "Update node request %s",
        node_id,
    )

    if node.id != node_id:
        raise HTTPException(
            status_code=422,
            detail="Node ID mismatch",
        )

    return network_service.update_node(
        node
    )



@router.delete(
    '/graph/nodes/{node_id}',
    tags=['Graph'],
)
def delete_node(node_id: str):
    logger.info(
        "Delete node request %s",
        node_id,
    )

    ok = network_service.delete_node(
        node_id
    )

    try:
        if not ok:
            raise HTTPException(
                status_code=404,
                detail="Node not found",
            )

        return {
            "success": True
        }
    except SocialTribeException as e:
        raise HTTPException(
            422,
            e.to_dict(),
        )


@router.get(
    '/graph/recommend/{user_id}',
    tags=['Graph'],
)
def get_recommendations(
        user_id: str, top_k: int = 10
):
    logger.info(
        "Recommendation request "
        "user=%s top_k=%d",
        user_id,
        top_k,
    )

    try:
        return analytics_service.get_friend_recommendation(
            user_id,
            top_k,
        )

    except SocialTribeException as e:
        logger.exception(
            "Recommendation failed"
        )

        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.get(
    '/graph/recommend/{user_id}/details',
    tags=['Graph'],
)
def get_recommendation_details(
        user_id: str, top_k: int = 10
):
    logger.info(
        "Recommendation details request "
        "user=%s",
        user_id,
    )

    try:
        return (
            analytics_service
            .get_friend_recommendation_details(
                user_id,
                top_k,
            )
        )

    except SocialTribeException as e:
        logger.exception(
            "Recommendation failed"
        )

        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.post(
    '/graph/shortest-path',
    tags=['Graph'],
)
def find_shortest_path(body: ShortestPathRequest):
    try:
        return analytics_service.shortest_path(
            body.source_id,
            body.target_id,
        )

    except SocialTribeException as e:

        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.get(
    '/graph/stats',
    tags=['Graph'],
)
async def stats():
    logger.debug(
        "Graph stats requested"
    )
    return network_service.stats()
