# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00

from services.layout_service import (
    LayoutService,
)

from schemas.layout import (
    LayoutRequest,
)
from fastapi import APIRouter,HTTPException


from core.exceptions import (
    SocialTribeException,
)

from core.graph_instance import (
    graph_service,
)

from logger_config import get_logger

logger = get_logger(__name__)

router = APIRouter(tags=['Layout'])

layout_service = LayoutService(
    graph_service
)

@router.post(
    '/graph/layout',
    tags=['Layout'],
)
def apply_layout(
    body: LayoutRequest,
):
    logger.info(
        "Layout API request "
        "algorithm=%s",
        body.algorithm,
    )
    try:
        return layout_service.apply_layout(
            body
        )

    except SocialTribeException as e:
        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.get(
    '/graph/layout/current',
    tags=['Layout'],
)
def get_current_layout():
    try:

        return layout_service.current_layout()

    except SocialTribeException as e:

        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )
