# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00

import asyncio

from fastapi import (
    WebSocket,
    WebSocketDisconnect,
    APIRouter,
    HTTPException
)

from core.log_stream import (
    log_stream,
)

from schemas.logs import (
    LogHistoryRequest,
)
from core.exceptions import (
    LogQueryError,
)

from services.log_service import (
    log_service,
)

from logger_config import get_logger

logger = get_logger(__name__)
router = APIRouter(tags=['Logs'])


@router.post(
    '/logs/query',
    tags=['Logs'],
)
def query_logs(
        req:
        LogHistoryRequest,
):
    try:
        return log_service.query_logs(
            req.filters,
            req.sort,
            req.pagination,
        )

    except LogQueryError as e:
        raise HTTPException(
            status_code=422,
            detail=e.to_dict(),
        )


@router.websocket(
    "/ws"
)
async def logs_ws(
        websocket: WebSocket,
):
    logger.info(
        "Log websocket connected"
    )

    await log_stream.connect(
        websocket
    )

    try:
        while True:
            await asyncio.sleep(
                3600
            )


    except WebSocketDisconnect:
        logger.info(
            "Log websocket disconnected"
        )
        log_stream.disconnect(
            websocket
        )
