# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00

from fastapi import APIRouter,HTTPException


from services.query_service import (
    QueryService,
)

from core.exceptions import (
    SocialTribeException,
)

from schemas.query import (
    QueryRequest,
)
router = APIRouter(tags=['Query'])

query_service = QueryService()


@router.post(
    '/graph/query/',
    tags=['Query'],
)
async def execute_plan(
        request: QueryRequest,
):
    try:

        return query_service.execute_plan(
            request,
        )

    except SocialTribeException as exc:

        raise HTTPException(
            status_code=422,
            detail=exc.to_dict(),
        )
