# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00

from core.graph_instance import (
    graph_service,
)

from schemas.analytics import (
    InfluenceMaximizationRequest,
)

from core.exceptions import (
    InvalidKValueError
)
from services.simulation_service import SimulationService

from schemas.simulation import (
    SimulationRunRequest,
)

from logger_config import get_logger
from core.exceptions import (
    SocialTribeException,
)

from fastapi import APIRouter,HTTPException


logger = get_logger(__name__)
router = APIRouter(tags=['Simulation'])

simulation_service = (
    SimulationService(
        graph_service
    )
)

@router.post(
    '/simulation/influence-maximization',
    tags=['Simulation'],
)
def influence_maximization(
    body: InfluenceMaximizationRequest,
):
    try:
        return {
            "success": True,
            "data":
                simulation_service
                .influence_maximization(
                    body.k,
                    body.method,
                )
        }


    except InvalidKValueError as e:
        raise HTTPException(
            status_code=422,
            detail={
                "success": False,
                "error": e.message,
                "code": "INVALID_K",
            },
        )

    except SocialTribeException as e:
        raise HTTPException(
            status_code=400,
            detail={
                "success": False,
                "error": e.message,
                "code": e.__class__.__name__,
            },
        )



@router.post(
    '/simulation/run',
    tags=['Simulation'],
)
def run_simulation(body: SimulationRunRequest):
    try:
        data = (
            simulation_service
            .run_once(
                model=body.model,
                probability=body.probability,
                threshold=body.threshold,
                max_ticks=body.maxTicks,
            )
        )

        return {
            "success": True,
            "data": data,
        }

    except SocialTribeException as e:
        raise HTTPException(
            422,
            e.to_dict(),
        )
