# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00

import time
from core.shutdown_manager import (
    shutdown_server,
)
from fastapi import (
    APIRouter,
)
from core.graph_instance import (
    graph_service,
)
from logger_config import (
    get_logger,
)

START_TIME = time.time()

logger = get_logger(__name__)

router = APIRouter(tags=['System'])


@router.get(
    '/health',
    tags=['System'],
)
async def health_check():
    graph_id = (
        graph_service
        .repository
        ._graph_id()
    )

    graphs = (
        len(
            graph_service
            .registry
            ._graphs
        )
    )

    return {
        "status": "pass",
        "version": "v2.0.0",
        "timestamp": int(time.time()),
        "uptime_seconds": int(
            time.time()
            - START_TIME
        ),
        "checks": {

            "graph_registry": {
                "status": "pass",
                "message": "Registry loaded",
                "details":
                    f"Graphs: {graphs}"
            },

            "storage_engine": {
                "status": "pass",
                "message":
                    "Storage engine connected"
            },

            "active_graph": {
                "status": (
                    "pass"
                    if graph_id
                    else "fail"
                ),
                "message": (
                    "Active graph available"
                    if graph_id
                    else "No active graph"
                ),
                "details": graph_id
            },

            "spatial_index": {
                "status": "pass",
                "message":
                    "Spatial index operational"
            },
        }
    }

@router.post(
    '/shutdown',
    tags=['System'],
)
def shutdown():
    logger.warning(
        "Shutdown API called"
    )

    shutdown_server()

    return {
        "status":
            "initiated",

        "message":
            "Shutdown initiated successfully",

        "timestamp":
            int(time.time()),

        "shutdown_initiated":
            True,
    }
