# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-28T05:46:24+00:00


import time

from fastapi import APIRouter,HTTPException

from logger_config import (
    get_logger,
)

from schemas.graph_view import (
    ViewportRequest,
    ViewportResponseWithMetadata,
)

from services.network_service import (
    NetworkService,
)

from core.graph_instance import (
    graph_service,
)

logger = get_logger(__name__)
router = APIRouter(tags=['Viewport'])

network_service = NetworkService(
    graph_service
)

@router.post(
    '/graph/viewport',
    tags=['Viewport'],
)
def get_viewport(body: ViewportRequest):
    logger.debug(
        "Viewport request "
        "x=%s y=%s w=%s h=%s zoom=%s",
        body.x,
        body.y,
        body.width,
        body.height,
        body.zoom,
    )

    if body.width <= 0:
        raise HTTPException(
            status_code=422,
            detail="width must be greater than 0",
        )

    if body.height <= 0:
        raise HTTPException(
            status_code=422,
            detail="height must be greater than 0",
        )

    start = time.time()

    response = network_service.viewport(
        body
    )

    elapsed = (
                      time.time()
                      - start
              ) * 1000

    return ViewportResponseWithMetadata(
        nodes=response["nodes"],
        edges=response["edges"],
        metadata={
            "query_time_ms":
                int(elapsed),

            "node_count":
                len(
                    response["nodes"]
                ),

            "edge_count":
                len(
                    response["edges"]
                ),

            "zoom":
                body.zoom,
        },
    )


@router.post(
    '/graph/viewport/batch',
    tags=['Viewport'],
)
def batch_viewport(body: list[ViewportRequest]):
    results = []

    for req in body:
        results.append(
            network_service.viewport(
                req
            )
        )

    return results

