# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-01T19:08:50+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any, Dict, List, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field, RootModel, confloat, conint


class ViewportRequest(BaseModel):
    x: float
    y: float
    width: float
    height: float
    zoom: float


class EdgeData(BaseModel):
    Weight: Optional[float] = Field(None, examples=[50])
    createdAt: Optional[AwareDatetime] = None
    id: Optional[str] = None
    targetId: Optional[str] = None


class NodeData(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    nodeType: Optional[str] = Field(None, examples=['socialUser'])
    role: Optional[str] = Field(None, examples=['normal'])
    friendCount: Optional[int] = None
    avgDistance: Optional[float] = None
    centrality: Optional[float] = None


class Position(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None


class ValidationErrorDetail(BaseModel):
    loc: Optional[List[Union[str, int]]] = None
    msg: Optional[str] = None
    type: Optional[str] = None
    input: Optional[str] = None
    ctx: Optional[Dict[str, Any]] = None


class CreateNodeRequest(BaseModel):
    id: str
    type: str = Field(..., examples=['socialUser'])
    position: Position
    data: NodeData


class UpdateNodeRequest(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = Field(None, examples=['socialUser'])
    position: Optional[Position] = None
    data: Optional[NodeData] = None


class CreateEdgeRequest(BaseModel):
    id: str
    source: str
    target: str
    type: str = Field(..., examples=['weightedEdge'])
    data: EdgeData


class Mode(StrEnum):
    switch = 'switch'
    merge = 'merge'


class ImportDatasetResponse(BaseModel):
    dataset_id: str
    graph_id: str
    mode: Mode
    total_nodes: int
    total_edges: int
    file_name: str
    saved: bool


class EnsembleConfig(BaseModel):
    resolution: Optional[float] = Field(
        1, description='Resolution parameter for community detection', examples=[1]
    )
    ensembleRuns: Optional[int] = Field(
        16, description='Number of ensemble runs', examples=[16]
    )
    consensusThreshold: Optional[float] = Field(
        0.5, description='Threshold for consensus clustering', examples=[0.5]
    )


class ShortestPathRequest(BaseModel):
    source_id: str = Field(
        ..., description='ID of the source node', examples=['node-1']
    )
    target_id: str = Field(
        ..., description='ID of the target node', examples=['node-2']
    )


class ApplyLayoutRequest(BaseModel):
    algorithm: str = Field(
        ..., description='Layout algorithm to apply', examples=['force-directed']
    )
    params: Optional[Dict[str, Any]] = Field(
        None,
        description='Additional parameters for the layout algorithm',
        examples=[{}],
    )


class LayoutNodePosition(RootModel[Dict[str, float]]):
    root: Dict[str, float]


class ExecutePlanRequest(BaseModel):
    plan: Dict[str, Any] = Field(..., description='Query execution plan', examples=[{}])


class QueryStatistics(BaseModel):
    scanned: Optional[int] = Field(
        None, description='Number of elements scanned', examples=[0]
    )
    traversed: Optional[int] = Field(
        None, description='Number of elements traversed', examples=[0]
    )
    filtered: Optional[int] = Field(
        None, description='Number of elements filtered', examples=[0]
    )
    execution_time_ms: Optional[float] = Field(
        None, description='Execution time in milliseconds', examples=[0]
    )


class CreateBackupRequest(BaseModel):
    name: str = Field(
        ..., description='Name for the backup', examples=['my-backup-2024']
    )


class RunSimulationRequest(BaseModel):
    model: str = Field(
        ..., description='Type of simulation model to run', examples=['wave']
    )
    probability: confloat(ge=0.0, le=1.0) = Field(
        ..., description='Probability parameter for the simulation', examples=[0.3]
    )
    threshold: conint(ge=1) = Field(
        ..., description='Threshold value for the simulation', examples=[2]
    )
    maxTicks: conint(ge=1) = Field(
        ..., description='Maximum number of simulation ticks', examples=[100]
    )


class Method(StrEnum):
    optimal = 'optimal'
    greedy = 'greedy'
    degree = 'degree'
    random = 'random'


class InfluenceMaximizationRequest(BaseModel):
    k: conint(ge=1) = Field(
        ..., description='Number of seed nodes to select', examples=[5]
    )
    method: Method = Field(
        ..., description='Method for influence maximization', examples=['optimal']
    )


class LogFilters(BaseModel):
    service: Optional[List[str]] = Field(
        None, description='List of services to filter by', examples=[[]]
    )
    level: Optional[List[str]] = Field(
        None, description='List of log levels to filter by', examples=[[]]
    )


class LogPagination(BaseModel):
    page: Optional[conint(ge=1)] = Field(1, description='Page number', examples=[1])
    pageSize: Optional[conint(ge=1, le=1000)] = Field(
        100, description='Number of items per page', examples=[100]
    )


class Order(StrEnum):
    asc = 'asc'
    desc = 'desc'


class LogSort(BaseModel):
    field: Optional[str] = Field(
        None, description='Field to sort by', examples=['timestamp']
    )
    order: Optional[Order] = Field(None, description='Sort order', examples=['desc'])


class GraphEdge(BaseModel):
    id: Optional[str] = None
    source: Optional[str] = None
    target: Optional[str] = None
    type: Optional[str] = Field(None, examples=['weightedEdge'])
    data: Optional[EdgeData] = None


class GraphNode(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = Field(None, examples=['socialUser'])
    position: Optional[Position] = None
    data: Optional[NodeData] = None


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationErrorDetail]] = None


class EnsembleCommunitiesRequest(BaseModel):
    config: EnsembleConfig


class LayoutNode(BaseModel):
    id: str
    position: LayoutNodePosition


class QueryData(BaseModel):
    rows: Optional[List[Dict[str, Any]]] = Field(None, description='Result rows')
    columns: Optional[List[str]] = Field(None, description='Column names')
    statistics: Optional[QueryStatistics] = None


class QueryLogsRequest(BaseModel):
    filters: Optional[LogFilters] = None
    sort: Optional[LogSort] = None
    pagination: Optional[LogPagination] = None


class ViewportResponse(BaseModel):
    nodes: Optional[List[GraphNode]] = None
    metadata: Optional[Dict[str, Any]] = None
    edges: Optional[List[GraphEdge]] = None


class ApplyLayoutResponse(BaseModel):
    nodes: List[LayoutNode]
    algorithm: str
    executionTimeMs: float = Field(..., description='Execution time in milliseconds')


class ExecutePlanResponse(BaseModel):
    success: bool = Field(
        ..., description='Whether the query executed successfully', examples=[True]
    )
    data: QueryData
