# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_engine.storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub:
    """---- Service Definition ----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNode = channel.unary_unary(
                '/storage.StorageService/CreateNode',
                request_serializer=storage__pb2.CreateNodeRequest.SerializeToString,
                response_deserializer=storage__pb2.CreateNodeResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/storage.StorageService/GetNode',
                request_serializer=storage__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=storage__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.GetNodeBulk = channel.unary_unary(
                '/storage.StorageService/GetNodeBulk',
                request_serializer=storage__pb2.GetNodeBulkRequest.SerializeToString,
                response_deserializer=storage__pb2.GetNodeBulkResponse.FromString,
                _registered_method=True)
        self.UpdateNode = channel.unary_unary(
                '/storage.StorageService/UpdateNode',
                request_serializer=storage__pb2.UpdateNodeRequest.SerializeToString,
                response_deserializer=storage__pb2.UpdateNodeResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/storage.StorageService/DeleteNode',
                request_serializer=storage__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=storage__pb2.DeleteNodeResponse.FromString,
                _registered_method=True)
        self.DeleteNodeBulk = channel.unary_unary(
                '/storage.StorageService/DeleteNodeBulk',
                request_serializer=storage__pb2.DeleteNodeBulkRequest.SerializeToString,
                response_deserializer=storage__pb2.DeleteNodeBulkResponse.FromString,
                _registered_method=True)
        self.ContainsNode = channel.unary_unary(
                '/storage.StorageService/ContainsNode',
                request_serializer=storage__pb2.ContainsNodeRequest.SerializeToString,
                response_deserializer=storage__pb2.ContainsNodeResponse.FromString,
                _registered_method=True)
        self.PeekNode = channel.unary_unary(
                '/storage.StorageService/PeekNode',
                request_serializer=storage__pb2.PeekNodeRequest.SerializeToString,
                response_deserializer=storage__pb2.PeekNodeResponse.FromString,
                _registered_method=True)
        self.CreateEdge = channel.unary_unary(
                '/storage.StorageService/CreateEdge',
                request_serializer=storage__pb2.CreateEdgeRequest.SerializeToString,
                response_deserializer=storage__pb2.CreateEdgeResponse.FromString,
                _registered_method=True)
        self.GetEdge = channel.unary_unary(
                '/storage.StorageService/GetEdge',
                request_serializer=storage__pb2.GetEdgeRequest.SerializeToString,
                response_deserializer=storage__pb2.GetEdgeResponse.FromString,
                _registered_method=True)
        self.GetEdgeBulk = channel.unary_unary(
                '/storage.StorageService/GetEdgeBulk',
                request_serializer=storage__pb2.GetEdgeBulkRequest.SerializeToString,
                response_deserializer=storage__pb2.GetEdgeBulkResponse.FromString,
                _registered_method=True)
        self.UpdateEdge = channel.unary_unary(
                '/storage.StorageService/UpdateEdge',
                request_serializer=storage__pb2.UpdateEdgeRequest.SerializeToString,
                response_deserializer=storage__pb2.UpdateEdgeResponse.FromString,
                _registered_method=True)
        self.DeleteEdge = channel.unary_unary(
                '/storage.StorageService/DeleteEdge',
                request_serializer=storage__pb2.DeleteEdgeRequest.SerializeToString,
                response_deserializer=storage__pb2.DeleteEdgeResponse.FromString,
                _registered_method=True)
        self.DeleteEdgeBulk = channel.unary_unary(
                '/storage.StorageService/DeleteEdgeBulk',
                request_serializer=storage__pb2.DeleteEdgeBulkRequest.SerializeToString,
                response_deserializer=storage__pb2.DeleteEdgeBulkResponse.FromString,
                _registered_method=True)
        self.ContainsEdge = channel.unary_unary(
                '/storage.StorageService/ContainsEdge',
                request_serializer=storage__pb2.ContainsEdgeRequest.SerializeToString,
                response_deserializer=storage__pb2.ContainsEdgeResponse.FromString,
                _registered_method=True)
        self.PeekEdge = channel.unary_unary(
                '/storage.StorageService/PeekEdge',
                request_serializer=storage__pb2.PeekEdgeRequest.SerializeToString,
                response_deserializer=storage__pb2.PeekEdgeResponse.FromString,
                _registered_method=True)
        self.GetDegree = channel.unary_unary(
                '/storage.StorageService/GetDegree',
                request_serializer=storage__pb2.GetDegreeRequest.SerializeToString,
                response_deserializer=storage__pb2.GetDegreeResponse.FromString,
                _registered_method=True)
        self.GetDegreeBatch = channel.unary_unary(
                '/storage.StorageService/GetDegreeBatch',
                request_serializer=storage__pb2.GetDegreeBatchRequest.SerializeToString,
                response_deserializer=storage__pb2.GetDegreeBatchResponse.FromString,
                _registered_method=True)
        self.HasEdge = channel.unary_unary(
                '/storage.StorageService/HasEdge',
                request_serializer=storage__pb2.HasEdgeRequest.SerializeToString,
                response_deserializer=storage__pb2.HasEdgeResponse.FromString,
                _registered_method=True)
        self.HasEdgeBatch = channel.unary_unary(
                '/storage.StorageService/HasEdgeBatch',
                request_serializer=storage__pb2.HasEdgeBatchRequest.SerializeToString,
                response_deserializer=storage__pb2.HasEdgeBatchResponse.FromString,
                _registered_method=True)
        self.GetEdgeWeight = channel.unary_unary(
                '/storage.StorageService/GetEdgeWeight',
                request_serializer=storage__pb2.GetEdgeWeightRequest.SerializeToString,
                response_deserializer=storage__pb2.GetEdgeWeightResponse.FromString,
                _registered_method=True)
        self.GetEdgeWeightsBatch = channel.unary_unary(
                '/storage.StorageService/GetEdgeWeightsBatch',
                request_serializer=storage__pb2.GetEdgeWeightsBatchRequest.SerializeToString,
                response_deserializer=storage__pb2.GetEdgeWeightsBatchResponse.FromString,
                _registered_method=True)
        self.GetCommonNeighbors = channel.unary_unary(
                '/storage.StorageService/GetCommonNeighbors',
                request_serializer=storage__pb2.GetCommonNeighborsRequest.SerializeToString,
                response_deserializer=storage__pb2.GetCommonNeighborsResponse.FromString,
                _registered_method=True)
        self.CountCommonNeighbors = channel.unary_unary(
                '/storage.StorageService/CountCommonNeighbors',
                request_serializer=storage__pb2.CountCommonNeighborsRequest.SerializeToString,
                response_deserializer=storage__pb2.CountCommonNeighborsResponse.FromString,
                _registered_method=True)
        self.GetNeighbors = channel.unary_unary(
                '/storage.StorageService/GetNeighbors',
                request_serializer=storage__pb2.GetNeighborsRequest.SerializeToString,
                response_deserializer=storage__pb2.GetNeighborsResponse.FromString,
                _registered_method=True)
        self.GetNeighborsBatch = channel.unary_unary(
                '/storage.StorageService/GetNeighborsBatch',
                request_serializer=storage__pb2.GetNeighborsBatchRequest.SerializeToString,
                response_deserializer=storage__pb2.GetNeighborsBatchResponse.FromString,
                _registered_method=True)
        self.GetNeighborsWithWeights = channel.unary_unary(
                '/storage.StorageService/GetNeighborsWithWeights',
                request_serializer=storage__pb2.GetNeighborsWithWeightsRequest.SerializeToString,
                response_deserializer=storage__pb2.GetNeighborsWithWeightsResponse.FromString,
                _registered_method=True)
        self.ShortestPath = channel.unary_unary(
                '/storage.StorageService/ShortestPath',
                request_serializer=storage__pb2.ShortestPathRequest.SerializeToString,
                response_deserializer=storage__pb2.ShortestPathResponse.FromString,
                _registered_method=True)
        self.IsNeighbor = channel.unary_unary(
                '/storage.StorageService/IsNeighbor',
                request_serializer=storage__pb2.IsNeighborRequest.SerializeToString,
                response_deserializer=storage__pb2.IsNeighborResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/storage.StorageService/GetStats',
                request_serializer=storage__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=storage__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.GetCacheStats = channel.unary_unary(
                '/storage.StorageService/GetCacheStats',
                request_serializer=storage__pb2.GetCacheStatsRequest.SerializeToString,
                response_deserializer=storage__pb2.GetCacheStatsResponse.FromString,
                _registered_method=True)
        self.ClearCache = channel.unary_unary(
                '/storage.StorageService/ClearCache',
                request_serializer=storage__pb2.ClearCacheRequest.SerializeToString,
                response_deserializer=storage__pb2.ClearCacheResponse.FromString,
                _registered_method=True)
        self.PrefetchViewport = channel.unary_unary(
                '/storage.StorageService/PrefetchViewport',
                request_serializer=storage__pb2.PrefetchViewportRequest.SerializeToString,
                response_deserializer=storage__pb2.PrefetchViewportResponse.FromString,
                _registered_method=True)


class StorageServiceServicer:
    """---- Service Definition ----
    """

    def CreateNode(self, request, context):
        """Node Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNodeBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContainsNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEdge(self, request, context):
        """Edge Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdgeBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEdgeBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContainsEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDegree(self, request, context):
        """Graph Operations (New)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDegreeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasEdgeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdgeWeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdgeWeightsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommonNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountCommonNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighborsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighborsWithWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShortestPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsNeighbor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Admin Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrefetchViewport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNode,
                    request_deserializer=storage__pb2.CreateNodeRequest.FromString,
                    response_serializer=storage__pb2.CreateNodeResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=storage__pb2.GetNodeRequest.FromString,
                    response_serializer=storage__pb2.GetNodeResponse.SerializeToString,
            ),
            'GetNodeBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeBulk,
                    request_deserializer=storage__pb2.GetNodeBulkRequest.FromString,
                    response_serializer=storage__pb2.GetNodeBulkResponse.SerializeToString,
            ),
            'UpdateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNode,
                    request_deserializer=storage__pb2.UpdateNodeRequest.FromString,
                    response_serializer=storage__pb2.UpdateNodeResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=storage__pb2.DeleteNodeRequest.FromString,
                    response_serializer=storage__pb2.DeleteNodeResponse.SerializeToString,
            ),
            'DeleteNodeBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNodeBulk,
                    request_deserializer=storage__pb2.DeleteNodeBulkRequest.FromString,
                    response_serializer=storage__pb2.DeleteNodeBulkResponse.SerializeToString,
            ),
            'ContainsNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ContainsNode,
                    request_deserializer=storage__pb2.ContainsNodeRequest.FromString,
                    response_serializer=storage__pb2.ContainsNodeResponse.SerializeToString,
            ),
            'PeekNode': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekNode,
                    request_deserializer=storage__pb2.PeekNodeRequest.FromString,
                    response_serializer=storage__pb2.PeekNodeResponse.SerializeToString,
            ),
            'CreateEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEdge,
                    request_deserializer=storage__pb2.CreateEdgeRequest.FromString,
                    response_serializer=storage__pb2.CreateEdgeResponse.SerializeToString,
            ),
            'GetEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdge,
                    request_deserializer=storage__pb2.GetEdgeRequest.FromString,
                    response_serializer=storage__pb2.GetEdgeResponse.SerializeToString,
            ),
            'GetEdgeBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdgeBulk,
                    request_deserializer=storage__pb2.GetEdgeBulkRequest.FromString,
                    response_serializer=storage__pb2.GetEdgeBulkResponse.SerializeToString,
            ),
            'UpdateEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEdge,
                    request_deserializer=storage__pb2.UpdateEdgeRequest.FromString,
                    response_serializer=storage__pb2.UpdateEdgeResponse.SerializeToString,
            ),
            'DeleteEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEdge,
                    request_deserializer=storage__pb2.DeleteEdgeRequest.FromString,
                    response_serializer=storage__pb2.DeleteEdgeResponse.SerializeToString,
            ),
            'DeleteEdgeBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEdgeBulk,
                    request_deserializer=storage__pb2.DeleteEdgeBulkRequest.FromString,
                    response_serializer=storage__pb2.DeleteEdgeBulkResponse.SerializeToString,
            ),
            'ContainsEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.ContainsEdge,
                    request_deserializer=storage__pb2.ContainsEdgeRequest.FromString,
                    response_serializer=storage__pb2.ContainsEdgeResponse.SerializeToString,
            ),
            'PeekEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekEdge,
                    request_deserializer=storage__pb2.PeekEdgeRequest.FromString,
                    response_serializer=storage__pb2.PeekEdgeResponse.SerializeToString,
            ),
            'GetDegree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDegree,
                    request_deserializer=storage__pb2.GetDegreeRequest.FromString,
                    response_serializer=storage__pb2.GetDegreeResponse.SerializeToString,
            ),
            'GetDegreeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDegreeBatch,
                    request_deserializer=storage__pb2.GetDegreeBatchRequest.FromString,
                    response_serializer=storage__pb2.GetDegreeBatchResponse.SerializeToString,
            ),
            'HasEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.HasEdge,
                    request_deserializer=storage__pb2.HasEdgeRequest.FromString,
                    response_serializer=storage__pb2.HasEdgeResponse.SerializeToString,
            ),
            'HasEdgeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.HasEdgeBatch,
                    request_deserializer=storage__pb2.HasEdgeBatchRequest.FromString,
                    response_serializer=storage__pb2.HasEdgeBatchResponse.SerializeToString,
            ),
            'GetEdgeWeight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdgeWeight,
                    request_deserializer=storage__pb2.GetEdgeWeightRequest.FromString,
                    response_serializer=storage__pb2.GetEdgeWeightResponse.SerializeToString,
            ),
            'GetEdgeWeightsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdgeWeightsBatch,
                    request_deserializer=storage__pb2.GetEdgeWeightsBatchRequest.FromString,
                    response_serializer=storage__pb2.GetEdgeWeightsBatchResponse.SerializeToString,
            ),
            'GetCommonNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommonNeighbors,
                    request_deserializer=storage__pb2.GetCommonNeighborsRequest.FromString,
                    response_serializer=storage__pb2.GetCommonNeighborsResponse.SerializeToString,
            ),
            'CountCommonNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.CountCommonNeighbors,
                    request_deserializer=storage__pb2.CountCommonNeighborsRequest.FromString,
                    response_serializer=storage__pb2.CountCommonNeighborsResponse.SerializeToString,
            ),
            'GetNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbors,
                    request_deserializer=storage__pb2.GetNeighborsRequest.FromString,
                    response_serializer=storage__pb2.GetNeighborsResponse.SerializeToString,
            ),
            'GetNeighborsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighborsBatch,
                    request_deserializer=storage__pb2.GetNeighborsBatchRequest.FromString,
                    response_serializer=storage__pb2.GetNeighborsBatchResponse.SerializeToString,
            ),
            'GetNeighborsWithWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighborsWithWeights,
                    request_deserializer=storage__pb2.GetNeighborsWithWeightsRequest.FromString,
                    response_serializer=storage__pb2.GetNeighborsWithWeightsResponse.SerializeToString,
            ),
            'ShortestPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ShortestPath,
                    request_deserializer=storage__pb2.ShortestPathRequest.FromString,
                    response_serializer=storage__pb2.ShortestPathResponse.SerializeToString,
            ),
            'IsNeighbor': grpc.unary_unary_rpc_method_handler(
                    servicer.IsNeighbor,
                    request_deserializer=storage__pb2.IsNeighborRequest.FromString,
                    response_serializer=storage__pb2.IsNeighborResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=storage__pb2.GetStatsRequest.FromString,
                    response_serializer=storage__pb2.GetStatsResponse.SerializeToString,
            ),
            'GetCacheStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheStats,
                    request_deserializer=storage__pb2.GetCacheStatsRequest.FromString,
                    response_serializer=storage__pb2.GetCacheStatsResponse.SerializeToString,
            ),
            'ClearCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCache,
                    request_deserializer=storage__pb2.ClearCacheRequest.FromString,
                    response_serializer=storage__pb2.ClearCacheResponse.SerializeToString,
            ),
            'PrefetchViewport': grpc.unary_unary_rpc_method_handler(
                    servicer.PrefetchViewport,
                    request_deserializer=storage__pb2.PrefetchViewportRequest.FromString,
                    response_serializer=storage__pb2.PrefetchViewportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService:
    """---- Service Definition ----
    """

    @staticmethod
    def CreateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/CreateNode',
            storage__pb2.CreateNodeRequest.SerializeToString,
            storage__pb2.CreateNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetNode',
            storage__pb2.GetNodeRequest.SerializeToString,
            storage__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetNodeBulk',
            storage__pb2.GetNodeBulkRequest.SerializeToString,
            storage__pb2.GetNodeBulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/UpdateNode',
            storage__pb2.UpdateNodeRequest.SerializeToString,
            storage__pb2.UpdateNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteNode',
            storage__pb2.DeleteNodeRequest.SerializeToString,
            storage__pb2.DeleteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNodeBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteNodeBulk',
            storage__pb2.DeleteNodeBulkRequest.SerializeToString,
            storage__pb2.DeleteNodeBulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContainsNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ContainsNode',
            storage__pb2.ContainsNodeRequest.SerializeToString,
            storage__pb2.ContainsNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeekNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/PeekNode',
            storage__pb2.PeekNodeRequest.SerializeToString,
            storage__pb2.PeekNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/CreateEdge',
            storage__pb2.CreateEdgeRequest.SerializeToString,
            storage__pb2.CreateEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetEdge',
            storage__pb2.GetEdgeRequest.SerializeToString,
            storage__pb2.GetEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdgeBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetEdgeBulk',
            storage__pb2.GetEdgeBulkRequest.SerializeToString,
            storage__pb2.GetEdgeBulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/UpdateEdge',
            storage__pb2.UpdateEdgeRequest.SerializeToString,
            storage__pb2.UpdateEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteEdge',
            storage__pb2.DeleteEdgeRequest.SerializeToString,
            storage__pb2.DeleteEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEdgeBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteEdgeBulk',
            storage__pb2.DeleteEdgeBulkRequest.SerializeToString,
            storage__pb2.DeleteEdgeBulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContainsEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ContainsEdge',
            storage__pb2.ContainsEdgeRequest.SerializeToString,
            storage__pb2.ContainsEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeekEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/PeekEdge',
            storage__pb2.PeekEdgeRequest.SerializeToString,
            storage__pb2.PeekEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDegree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetDegree',
            storage__pb2.GetDegreeRequest.SerializeToString,
            storage__pb2.GetDegreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDegreeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetDegreeBatch',
            storage__pb2.GetDegreeBatchRequest.SerializeToString,
            storage__pb2.GetDegreeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/HasEdge',
            storage__pb2.HasEdgeRequest.SerializeToString,
            storage__pb2.HasEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasEdgeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/HasEdgeBatch',
            storage__pb2.HasEdgeBatchRequest.SerializeToString,
            storage__pb2.HasEdgeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdgeWeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetEdgeWeight',
            storage__pb2.GetEdgeWeightRequest.SerializeToString,
            storage__pb2.GetEdgeWeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdgeWeightsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetEdgeWeightsBatch',
            storage__pb2.GetEdgeWeightsBatchRequest.SerializeToString,
            storage__pb2.GetEdgeWeightsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommonNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetCommonNeighbors',
            storage__pb2.GetCommonNeighborsRequest.SerializeToString,
            storage__pb2.GetCommonNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountCommonNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/CountCommonNeighbors',
            storage__pb2.CountCommonNeighborsRequest.SerializeToString,
            storage__pb2.CountCommonNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetNeighbors',
            storage__pb2.GetNeighborsRequest.SerializeToString,
            storage__pb2.GetNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighborsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetNeighborsBatch',
            storage__pb2.GetNeighborsBatchRequest.SerializeToString,
            storage__pb2.GetNeighborsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighborsWithWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetNeighborsWithWeights',
            storage__pb2.GetNeighborsWithWeightsRequest.SerializeToString,
            storage__pb2.GetNeighborsWithWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShortestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ShortestPath',
            storage__pb2.ShortestPathRequest.SerializeToString,
            storage__pb2.ShortestPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsNeighbor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/IsNeighbor',
            storage__pb2.IsNeighborRequest.SerializeToString,
            storage__pb2.IsNeighborResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetStats',
            storage__pb2.GetStatsRequest.SerializeToString,
            storage__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GetCacheStats',
            storage__pb2.GetCacheStatsRequest.SerializeToString,
            storage__pb2.GetCacheStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ClearCache',
            storage__pb2.ClearCacheRequest.SerializeToString,
            storage__pb2.ClearCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrefetchViewport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/PrefetchViewport',
            storage__pb2.PrefetchViewportRequest.SerializeToString,
            storage__pb2.PrefetchViewportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
